version: "3.9"

services:

  fastapi:
    container_name: onedrive
    build:
      context: .
      dockerfile: ./config/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - .:/app
